services:
  prefect-server:
    image: prefecthq/prefect:3.4.7-python3.11
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    networks:
      - rust_kafka_kafka-net

  prefect-agent:
    build: .
    depends_on:
      - prefect-server
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - rust_kafka_kafka-net

networks:
  rust_kafka_kafka-net:
    external: true